# docker-compose.yml
# Простой и понятный compose без поля "version" (оно устарело).

services:
  # ====================== PostgreSQL ======================
  farmer_db:                                   # имя сервиса БД
    image: postgres:15
    container_name: farmer_db           # удобное имя контейнера
    restart: always
    environment:
      POSTGRES_DB: farmer_markets       # имя базы
      POSTGRES_USER: app_user           # пользователь
      POSTGRES_PASSWORD: app_pass       # пароль
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # volume для сохранности данных

  # ====================== Streamlit (как было) ======================
  app:
    build: .
    container_name: farmer_app
    restart: always
    depends_on:
      - farmer_db                               # <<< ИМЕННО "db"
    environment:
      DB_NAME: farmer_markets
      DB_USER: app_user
      DB_PASSWORD: app_pass
      DB_HOST: farmer_db
      DB_PORT: 5432
      APP_MODE: "streamlit"
    working_dir: /app
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    volumes:
      - .:/app                            # монтируем весь проект
    ports:
      - "8501:8501"

  # ====================== Django ======================
  farmer_django:
    build: .
    container_name: farmer_django
    restart: always
    depends_on:
      - farmer_db                                # <<< ИМЕННО "db"
    environment:
      DJANGO_SETTINGS_MODULE: fm_project.settings
      PYTHONUNBUFFERED: "1"
      DEBUG: "1"
      ALLOWED_HOSTS: "127.0.0.1,localhost"
      DB_HOST: farmer_db
      DB_PORT: 5432
      DB_NAME: farmer_markets
      DB_USER: app_user
      DB_PASSWORD: app_pass
      APP_MODE: "django"                  # режим для entrypoint (если используете)
    working_dir: /web                     # здесь лежит manage.py
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    command: >
      sh -lc "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8502"
    volumes:
      - .:/app                            # чтобы был доступен /app/entrypoint.sh
      - ./web:/web                        # чтобы /web/manage.py был внутри контейнера
    ports:
      - "8502:8502"

# ====================== Volume для БД ======================
volumes:
  pgdata:
